bowtie:
  - 1.2.0
bowtie2:
  - 2.3.0
blat:
  - 35
bwa:
  - 0.7.12
velvet:
  - 1.2.10
openpyxl:
  - 2.5.0a2
xlrd:
  - 1.0.0
pigz:
  - 2.3
samtools:
  - 0.1.19
picard:
  - 2.10.6
numpy:
  - 1.13.1
parallel:
  - 20171222

pin_run_as_build:
  bowtie:
    min_pin: x.x.x
    max_pin: x.x.x
  bowtie2:
    min_pin: x.x.x
    max_pin: x.x.x
  blat:
    min_pin: x
    max_pin: x
  bwa:
    min_pin: x.x.x
    max_pin: x.x.x
  velvet:
    min_pin: x.x.x
    max_pin: x.x.x
  openpyxl:
    min_pin: x.x.x
    max_pin: x.x.x
  xlrd:
    min_pin: x.x.x
    max_pin: x.x.x
  pigz:
    min_pin: x.x
    max_pin: x.x
  samtools:
    min_pin: x.x.x
    max_pin: x.x.x
  picard:
    min_pin: x.x.x
    max_pin: x.x.x
  numpy:
    min_pin: x.x.x
    max_pin: x.x.x
  parallel:
    min_pin: x
    max_pin: x
